server:
  port: 8084
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    #服务在注册中心的名称 不同服务名称不能重复
    name: cloud-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    solr:
      host: http://127.0.0.1:8080/solr
